name: Test

on:
  push:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Check
        run: npm run check
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test-coverage
      - name: Coverage
        uses: codecov/codecov-action@v2
